arm_trajectory_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 0.02
    joint_1: {trajectory: 0.05, goal: 0.01}
    joint_2: {trajectory: 0.05, goal: 0.01}
    joint_3: {trajectory: 0.05, goal: 0.01}
    joint_4: {trajectory: 0.05, goal: 0.01}
    joint_5: {trajectory: 0.05, goal: 0.01}
    joint_6: {trajectory: 0.05, goal: 0.01}
  gains:
    joint_1: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 1}
    joint_2: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 1}
    joint_3: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 1}
    joint_4: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 1}
    joint_5: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 1}
    joint_6: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 1}
      

    
#gazebo_ros_control:
#  pid_gains:
#    joint_1: {p: 10, i: 0.01, d: 0.0, i_clamp: 1}
#    joint_2: {p: 10, i: 0.01, d: 0.0, i_clamp: 1}
#    joint_3: {p: 10, i: 0.01, d: 0.0, i_clamp: 1}
#    joint_4: {p: 10, i: 0.01, d: 0.0, i_clamp: 1}
#    joint_5: {p: 10, i: 0.01, d: 0.0, i_clamp: 1}
#    joint_6: {p: 10, i: 0.01, d: 0.0, i_clamp: 1}
