# Publish all joint states -----------------------------------
#joint_state_controller:
#  type: joint_state_controller/JointStateController
#  publish_rate: 50 

# Position Controllers ---------------------------------------
gripper_controller:
  type: effort_controllers/JointPositionController
  joint: finger_joint
  pid: {p: 10.0, i: 0.0, d: 0.01}
  

# the following gains are used by the gazebo_mimic_joint plugin  
gazebo_ros_control:
  pid_gains:  
    right_outer_knuckle_joint:
      p: 20.0
      i: 0.01
      d: 0.01
      i_clamp: 1


