
  
gripper_controller:
  type: effort_controllers/JointGroupPositionController
  joints: 
    - finger_joint
    - right_outer_knuckle_joint
  finger_joint:
    pid: {p: 0.5, i: 0.0, d: 0.1, i_clamp: 1}  # p 0.5 d 0.1
  right_outer_knuckle_joint:
    pid: {p: 0.5, i: 0.0, d: 0.1, i_clamp: 1}

#gazebo_ros_control:
#  pid_gains:
#    finger_joint: {p: 1.0, i: 0.0, d: 0.1, i_clamp: 1}
#    right_outer_knuckle_joint: {p: 1.0, i: 0.0, d: 0.1, i_clamp: 1}
